### ISSUE TITLE
KVM Analysis Never Starts

### ISSUE THREAD

**Issue by hackdefendr** [ctxis/CAPE#401]
```
2019-09-04 09:23:11,633 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
2019-09-04 09:23:11,682 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
2019-09-04 09:23:15,710 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=2, and max_vmstartup_count=2
2019-09-04 09:23:16,263 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2019-09-04 09:23:16,272 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
```

Host: Debian 10
VM: Windows 10 x64
VM Config:  UAC disabled, Firewall Disabled, Defender Disabled
Machinery: KVM

Not sure why, but when using KVM as my machinery, the analysis never starts.  It just sits there waiting for analysis tasks, despite showing 1 pending task.

Is there a way to enable debug logging so I can maybe see what isn't happening?

**Comment by doomedraven** [comment]
Nothing to see with kvm, i would say peoblem how you run webserver and it
uses different db or problem with permissions, are the taskd are in pending
at least?

**Comment by hackdefendr** [comment]
I have 1 pending task and now I get a error when trying to submit additional tasks.

Will cuckoo (CAPE) run without a database connection?

**Comment by doomedraven** [comment]
Yes it runs on sqlite3 then, but if ypu change config for hypervisor, you
should restart cuckoo. Py and run them all with - d for more info

**Comment by hackdefendr** [comment]
Ok ran with -d and see no errors.  This is strange, it see's the machinery, and says its ready for analysis tasks, but just won't start.  Btw that pending task never times out, its still pending.

**Comment by hackdefendr** [comment]
What is "max_analysis_count=0" and why is it always 0, even when I start cuckoo with -m 3?

I'm grasping at straw.  Seems there is obviously something not happening, but no amount of debug info is going to help. 

What piece of all the dependencies for cuckoo actually launches the analysis?  Possible I have a broken dependency.

**Comment by doomedraven** [comment]
0 is for ullimited

Remove and rexonfigure everything from 0 should be the more easier solutiin
for you

**Comment by hackdefendr** [comment]
I just did a bunch of stuff and of course I have no idea which things worked.  I'll never learn!!

Anyway, I made some progress.  Now I am seeing a permission issue with submitted files:

```
2019-09-04 13:54:17,706 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
2019-09-04 13:54:17,823 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
2019-09-04 13:54:28,300 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=2, and max_vmstartup_count=2
2019-09-04 13:54:29,389 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2019-09-04 13:54:29,397 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-09-04 14:03:30,545 [lib.cuckoo.core.scheduler] INFO: Task #1: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_p5TGRH/102.bin'
2019-09-04 14:03:30,562 [lib.cuckoo.core.scheduler] ERROR: Task #1: Failure in AnalysisManager.run: [Errno 13] Permission denied: u'/tmp/cuckoo-tmp/upload_p5TGRH/102.bin'
Traceback (most recent call last):
  File "/opt/CAPE/lib/cuckoo/core/scheduler.py", line 472, in run
    success = self.launch_analysis()
  File "/opt/CAPE/lib/cuckoo/core/scheduler.py", line 256, in launch_analysis
    if not self.check_file():
  File "/opt/CAPE/lib/cuckoo/core/scheduler.py", line 112, in check_file
    sha256 = File(self.task.target).get_sha256()
  File "/opt/CAPE/lib/cuckoo/common/objects.py", line 194, in get_sha256
    if not self._sha256: self.calc_hashes()
  File "/opt/CAPE/lib/cuckoo/common/objects.py", line 145, in calc_hashes
    for chunk in self.get_chunks():
  File "/opt/CAPE/lib/cuckoo/common/objects.py", line 131, in get_chunks
    with open(self.file_path, "rb") as fd:
IOError: [Errno 13] Permission denied: u'/tmp/cuckoo-tmp/upload_p5TGRH/102.bin'
```

Should processing be run as root?  Is that why my submitted file is owned by root and not my cuckoo user?

**Comment by hackdefendr** [comment]
OK fixed the permission issue...forgot I was still running the web portion from the command line as root.

Now it appears that some folders are not getting created:

```
2019-09-04 14:15:02,367 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
2019-09-04 14:15:02,390 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt                                           nt=2
2019-09-04 14:15:03,258 [root] INFO: Updated running task ID 1 status to failed_analysis
2019-09-04 14:15:03,266 [lib.cuckoo.core.scheduler] INFO: Using "kvm" machine manager with max_analysis_count=0, max_machines_count=2, and max_vmstartup_count=2
2019-09-04 14:15:03,506 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2019-09-04 14:15:03,513 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-09-04 14:20:15,614 [lib.cuckoo.core.scheduler] INFO: Task #2: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_nZkFLn/102.bin'
2019-09-04 14:20:15,750 [lib.cuckoo.core.scheduler] INFO: Task #2: acquired machine win10 (label=win10)                                                     nt=2
2019-09-04 14:20:35,741 [lib.cuckoo.core.scheduler] INFO: Enabled route 'none'
2019-09-04 14:20:36,284 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 4535 (interface=virbr0, host=192.168.122.187, dump path=/opt/CAPE/storage/analyses/2/dump.pcap)
2019-09-04 14:20:36,485 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=win10, ip=192.168.122.187)
2019-09-04 14:20:54,065 [lib.cuckoo.core.guest] INFO: Uploading support files to guest (id=win10, ip=192.168.122.187)
2019-09-04 14:25:14,786 [lib.cuckoo.core.scheduler] ERROR: The analysis hit the critical timeout, terminating.                                              nt=2
2019-09-04 14:25:17,030 [lib.cuckoo.common.objects] WARNING: Unable to import yara (please compile from sources)
2019-09-04 14:25:17,360 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path "/opt/CAPE/storage/analyses/2/logs".
2019-09-04 14:25:17,363 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Dropped":
Traceback (most recent call last):
  File "/opt/CAPE/lib/cuckoo/core/plugins.py", line 197, in process                                                                                         nt=2
    data = current.run()
  File "/opt/CAPE/modules/processing/dropped.py", line 28, in run
    file_names = os.listdir(self.dropped_path)
OSError: [Errno 2] No such file or directory: '/opt/CAPE/storage/analyses/2/files'                                                                          5TGRH/102.bin'
2019-09-04 14:25:19,255 [modules.processing.suricata] WARNING: Suricata returned a Exit Value Other than Zero 4/9/2019 -- 14:25:19 - <Error> - [ERRCODE: SC_ERR_LOGDIR_CMDLINE(117)] - The logging directory "/opt/CAPE/storage/analyses/2/logs" supplied at the commandline (-l /opt/CAPE/storage/analyses/2/logs) doesn't exist. Shutting down the engine.

2019-09-04 14:25:20,714 [lib.cuckoo.core.plugins] WARNING: The reporting module "ReportPDF" returned the following error: Failed to generate PDF report: Neither wkhtmltopdf nor Weasyprint Python library are installed
2019-09-04 14:25:21,290 [lib.cuckoo.core.scheduler] INFO: Task #2: reports generation completed (path=/opt/CAPE/storage/analyses/2)
2019-09-04 14:25:21,354 [lib.cuckoo.core.scheduler] INFO: Task #2: analysis procedure completed
```

**Comment by doomedraven** [comment]
chown cuckoo:cuckoo /opt/CAPE -r

And make sure all executed aunder the same user thats all

**Comment by hackdefendr** [comment]
I have double and triple checked permissions.
I have double and triple checked that the processes are run by the cuckoo user, except for the rooter.py process.

I am still seeing this error:

`2019-09-04 15:29:35,583 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path "/opt/CAPE/storage/analyses/3/logs"`

So it isn't creating the folder structure under /opt/CAPE/storage.  Because of this, suricata isn't completing, and my final report page is completely unreadable.

**Comment by doomedraven** [comment]
what do you mean "completely unreadable"? well if no logs, not behavior, idk why, you would need to use debug trick and start analyzer.py by hand

start cuckoo as this
`CUCKOO_DBG=1 python cuckoo.py -d`

then add an task but disable human interaction, open vm view, and go to c:\<cuckoo folder>\analyzer.py execute analyzer and you will see, there should be some problems, do you have log on webgui in analysis?

**Comment by hackdefendr** [comment]
Here is my process.log:

[processing.log](https://github.com/ctxis/CAPE/files/3576406/processing.log)

**Comment by doomedraven** [comment]
well that isn't needed i need analyzer log not processing

**Comment by hackdefendr** [comment]
Completely unreadable means there is no summary page, just a giant django error page.

As I said,  cuckoo has the right permissions and is being run by the correct user. I don't need to debug what I originally opened this issue about. This issue has evolved into something new.

CAPE is not creating the proper folder structure under /opt/CAPE/storage/ ... its clearly stated in the error I posted earlier. "WARNING: Analysis results folder does not exist at path "/opt/CAPE/storage/analyses/3/logs"

If that path doesn't exist, there is no place to store logs and other files required to complete the analysis.  I don't see how this can be misunderstood.

**Comment by doomedraven** [comment]
well your error page has error description so you need to solve that

**Comment by hackdefendr** [comment]
Here is my cuckoo.log:

[cuckoo.log](https://github.com/ctxis/CAPE/files/3576446/cuckoo.log)

There is no analysis.log because the paths are not being created to place that log file into.

**Comment by hackdefendr** [comment]
Here is the django error page:

[django_error_page.txt](https://github.com/ctxis/CAPE/files/3576462/django_error_page.txt)

**Comment by doomedraven** [comment]
from cuckoo logs looks like you have processing=on in cuckoo.conf and started process.py


well what i can tell you, `rm -r /opt/CAPE`
get this script, modify few valuesin the top if needed
https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh
then just 
`chmod a+x cuckoo.sh && sudo ./cuckoo.sh  all CAPE`

and you will have a good setup

**Comment by doomedraven** [comment]
idk what you changed that everything is broken

**Comment by hackdefendr** [comment]
First, I didn't change any of the code, only my configuration files.  Second, I am not redoing everything from scratch. I followed the instructions from the docs folder, if that documentation isn't good enough, maybe those documents should be removed in favor of your script.

If you don't want to or cannot help, then let someone else have a go.

In the meantime, I will roll back each change I made until the summary page comes back correctly. Noting that the main dashboard and submit web pages look fine, it is only the analysis summary page that is broken.

**Comment by doomedraven** [comment]
lol i didn't told i don't want to help, the problem is what you have changed something somewhere, configs is part of code ;)

lets see if you will be lucky and can solve that easilly
yep the docs are very old and nobody cares about them, a lot of people just using my script and soon it will be part of deployment instruction in readme

**Comment by kevoreilly** [comment]
I am wondering if there isn't something up with the machinery module. Seems it's not getting past an attempt to call up the target vm. It might be possible to add some debug lines to modules/machinery/kvm.py to try to see what's going on there...

This missing files/folders would only be created after an analysis has run in the vm, so we should ensure we first see the message from cape to kvm getting through.

**Comment by doomedraven** [comment]
@kevoreilly xD how the hell then all our kvm servers are running?

**Comment by doomedraven** [comment]
@hackdefendr post your configs so maybe we can check spot what is wrong

**Comment by hackdefendr** [comment]
I don't want to chase down the wrong things so let's make sure we are all on the same page. KVM machinery is launching the VM now.  It just hits the timeout every time and then won't finish the analysis. Not worried about suricata yet, I can fix that. 

What most concerns me is the folder structure not being created.  Shouldn't at least the log and files folder be created during the analysis?

Here are the pertinent configs:

[CAPE.zip](https://github.com/ctxis/CAPE/files/3579548/CAPE.zip)

**Comment by doomedraven** [comment]
ok from that you was need to start, you using win10, and nobody told that is supported yet ;), go for win7 

another bug
cuckoo.conf
ip = 0.0.0.0 

but no result server ip set in kvm.conf, set it in cuckoo.conf and that should fix a lot of your problems

**Comment by hackdefendr** [comment]
CAPE won't start when I set an IP other than 0.0.0.0,  I get an error stating cannot bind to IP.

**Comment by doomedraven** [comment]
thats is totally __FALSE!__ did you tried ip = 192.168.122.1 if yes and it fails ,then you have problems with our OS __not CAPE__

**Comment by doomedraven** [comment]
at least you could also read the comments in kvm.conf which you removed, there is specified if you set to 0.0.0.0 you need to set it

**Comment by hackdefendr** [comment]
192.168.122.1 is the gateway for virbr0 interface.  Can't use that IP.

My kvm.conf does have the IP set.

**Comment by doomedraven** [comment]
yep and is correct

```
virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether X  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

so you should set that as ip of result server

bcz you removed a lot of stuff from kvm.conf get original kvm.conf from repo and you will see it

**Comment by doomedraven** [comment]
and why you can't use that ip? if vms are in that network you __SHOULD__ use that ip

**Comment by hackdefendr** [comment]
Now the web ui dashboard looks like crap again.  No graphics only text. What version of django was used when coding the web ui?  The requirements.txt says django>=1.7 and I have 1.11.24 installed.

**Comment by doomedraven** [comment]
your versions if fine, you need to see what is wrong with setup in manager.py logs where you started the webgui

**Comment by hackdefendr** [comment]
Where are the manage.py logs?

**Comment by doomedraven** [comment]
how did you start webgui?

**Comment by kevoreilly** [comment]
Ok well it sounds like progress has been made since the KVM issue :-D

Maybe it's the now between target vm and resultsserver - once that's solved the folder issue may clear up.

**Comment by hackdefendr** [comment]
Systemd -- cuckoo-wsgi.service

**Comment by doomedraven** [comment]
/var/log/syslog there your log, start it from web folder by hand `python manager.py runserver 0.0.0.0:8000` and thats all, make it works by hand all before you start systemd, is the same when you change configs, did you reload systemd deamons and restarting them?

**Comment by doomedraven** [comment]
i strongly suggest you disable systemd, and run all by hand, once you have fully working system then you can go to systemd

**Comment by hackdefendr** [comment]
Ok now the analysis completes, but something is still broken.  My log is filled with this:

```
2019-09-05 09:56:10,511 [Processing.Pcap] ERROR: Failed to process packet: invalid header length
Traceback (most recent call last):
  File "/opt/CAPE/modules/processing/network.py", line 741, in run
    tcp = dpkt.tcp.TCP(tcp)
  File "/usr/lib/python2.7/dist-packages/dpkt/dpkt.py", line 89, in __init__
    self.unpack(args[0])
  File "/usr/lib/python2.7/dist-packages/dpkt/tcp.py", line 66, in unpack
    raise dpkt.UnpackError('invalid header length')
UnpackError: invalid header length
```

[cuckoo.log](https://github.com/ctxis/CAPE/files/3579884/cuckoo.log)

**Comment by hackdefendr** [comment]
The folder structure is fixed now ... I'm guessing the result server IP fixed it.

**Comment by kevoreilly** [comment]
Happy days! :-)

**Comment by hackdefendr** [comment]
Any ideas as to what that "invalid header length" error is?

**Comment by doomedraven** [comment]
Google it you will answer im afk

**Comment by hackdefendr** [comment]
The error is coming from network.py or dpkt.py.  I'm not going to try and fix your code.

**Comment by kevoreilly** [comment]
I suspect this might turn out to be due to something outside of cape's codebase...

**Comment by doomedraven** [comment]
ok @hackdefendr  im gonna be direct and rude, got tired of that shit! that isnt' cape bug if you would google it, and ok as you told no fixing your code, why the hell we should help you now then? :D 

complain about docs when you not even read comments in confs and broke you setup and just complain over and over about your problems which you generated bcz you don't know how to use something. complain about what i was trying to help, cool now im really gonna leave you alone, you not collaborating with open source and only abuse it, being rude with this f**king attitude no more help from me to you, good luck

**Comment by kevoreilly** [comment]
The original problem is solved, closing.

**Comment by hackdefendr** [comment]
fuck off @doomedraven

**Comment by doomedraven** [comment]
@hackdefendr ololo that attitude,

**Comment by hackdefendr** [comment]
I googled the error and there is nothing specific to it. In fact, there is no solution for many pages on google.  Why don't you learn some communication skills and stop being such a dick.

**Comment by hackdefendr** [comment]
By the way for those following along...this problem IS NOT SOLVED.

**Comment by doomedraven** [comment]
there is, bcz i googled it in past many times, ROFL, read your msgs and how you behaves, you are alone, idk care anymore to help you with this attitude, people need ask stupid question to solve problems and as you maybe now saw it helped you, problem solved, problem is between the chair and keyboard ROFL, as you removed stuff and now complains over and over, __nobody anymore from devs care to help you__ so good luck with this behaviour and attitude

**Comment by hackdefendr** [comment]
Provide a link then if you are so smart.

**Comment by doomedraven** [comment]
rofl no help anymore, you gained it! and im unsubscribing from this to not see your msgs anymore

**Comment by hackdefendr** [comment]
So you aren't smart. Got it.

**Comment by doomedraven** [comment]
if you so f**cking smart why do you need help from other people, why you don't fix everything by yourself eh? ;) "the smartest person ever"

**Comment by hackdefendr** [comment]
Because I am a user not a coder dumb ass.  Some people are users and some are coders.  I can usually figure stuff out, but when YOUR code produces pages and pages of errors, that is out of my expertise. I opened this issue because I don't know all the answers and don't know all YOUR code.  

I was met with attitude from you at the very beginning saying I needed to delete everything and use your script to do over.  That is why I took attitude with you. 

Like I said...you need to learn how to communicate better and stop believing your code is error free and works on every system.

**Comment by kevoreilly** [comment]
I can honestly say that @doomedraven is doing just fine as he is, the cape project owes him a great debt of gratitude for his immeasurable contributions and support! He is also very helpful on the forums/issues, I won't hear otherwise!

**Comment by doomedraven** [comment]
@hackdefendr ROFL ROFL ROFL

>>I was met with attitude from you at the very beginning saying I needed to delete everything and use your script to do over. That is why I took attitude with you.

__that was totally true__, bcz read the errors, __you deleted stuff from config__, __code works just fine if you don't break it!__ and is why i suggested to use my script, but as your __ego__ doesn't allow you to understand that, that is your problem, not mine! so if you would reinstall you will see the comments in configs, reread all what i helped to solve you and now think again before speak.

but well you showed how you appreciate people spending free time on you to help and how you care about opensource. that was more than enough to stop helping you in your entire life
